# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 01:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbr', models.CharField(max_length=10)),
                ('rank', models.IntegerField(unique=True)),
                ('no_courses', models.IntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Examination')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('teller_no', models.CharField(max_length=10)),
                ('balance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TuitionFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('teller_no', models.CharField(max_length=10)),
                ('balance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(help_text='Maximum of 1mb.(100x100px)', upload_to='photos/%Y/%m/%d')),
                ('surname', models.CharField(max_length=30)),
                ('other_names', models.CharField(max_length=70)),
                ('reg_no', models.CharField(max_length=20)),
                ('email', models.EmailField(default='-', max_length=254)),
                ('sex', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1)),
                ('phone', models.CharField(max_length=13)),
                ('empoyers_name', models.CharField(max_length=50)),
                ('contact_address', models.TextField()),
                ('contacts_details', models.TextField(verbose_name='In case of emergency, contact person NAME, ADDRESS, PHONE')),
                ('institutions', models.TextField(verbose_name='Schools attended till date')),
                ('date_passed', models.DateField(verbose_name='Date last level was passed/exempted')),
                ('exam_date', models.DateField()),
                ('sponsor', models.CharField(max_length=30)),
                ('sponsor_signature', models.ImageField(help_text='Maximum of 1mb.(100x100px)', upload_to='photos/%Y/%m/%d')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(to='userprofile.Course')),
                ('current_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Level', verbose_name='Level to be attempted')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Examination')),
                ('last_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last-level+', to='userprofile.Level', verbose_name='Last level passed/exempted')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tuitionfee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='registrationfee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Level'),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set([('name', 'rank')]),
        ),
    ]
