# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-25 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20190325_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationfee',
            old_name='date',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='tuitionfee',
            old_name='date',
            new_name='payment_date',
        ),
    ]
